"""Golden-audio ASR accuracy test — the ONLY test that asserts transcription
quality against known speech (the rest of the suite mocks whisper or feeds silence).

Opt-in and slow: gated behind ``WAYFINDER_GOLDEN=1`` and the ``slow`` marker, so it
never runs in the default/CI gate. It transcribes the synthetic golden corpus
(tests/golden_audio/, generated by generate.py) with the REAL whisper-cli and asserts
a per-clip Word Error Rate ceiling + key-phrase survival. Raw ASR only — post-
processing is OFF so a regression in the model/prompt/artifact-cleanup is not masked
by the LLM tidy-up.

Run it:
    WAYFINDER_GOLDEN=1 .venv/bin/pytest tests/test_golden_asr.py -q
Regenerate the corpus first if it's missing:
    PYTHONPATH=src python tests/golden_audio/generate.py
"""
import os
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
for _p in (_REPO / "scripts", _REPO / "tests" / "golden_audio"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from tone_eval.metrics import wer, phrase_hits  # noqa: E402
from manifest import CLIPS, clip_path  # noqa: E402

_GOLDEN_ENABLED = os.environ.get("WAYFINDER_GOLDEN") == "1"

pytestmark = [
    pytest.mark.slow,
    pytest.mark.skipif(
        not _GOLDEN_ENABLED,
        reason="golden-audio ASR is opt-in; set WAYFINDER_GOLDEN=1 to run",
    ),
]

# WER slack allowed on the premium (turbo/GPU) path relative to the free-tier
# aggregate. Aggregate/advisory, NOT per-clip: on a short clean clip base.en can
# legitimately match or beat turbo, so a per-clip premium<=free rule would flake.
_PREMIUM_AGG_EPS = 0.03


def _find_whisper_cli():
    for p in (Path.home() / "whisper.cpp/build/bin/whisper-cli",
              Path("/usr/bin/whisper-cli"),
              Path("/app/bin/whisper-cli"),
              Path("/app/bin/whisper-cli-cpu")):
        if p.exists():
            return str(p)
    return None


def _find_model(names):
    dirs = (Path.home() / "whisper.cpp/models",
            Path.home() / ".local/share/wayfinder-aura/whisper-models",
            Path.home() / ".local/share/whisper.cpp",
            Path("/app/share/whisper-models"))
    for d in dirs:
        for n in names:
            p = d / n
            if p.exists():
                return str(p)
    return None


def _gpu_present():
    """Cheap, model-independent GPU presence check (mirrors the app's nudge gate)."""
    try:
        import wayfinder_main
        return wayfinder_main.get_gpu_info().has_gpu
    except Exception:
        return False


_CLI = _find_whisper_cli()
_BASE_MODEL = _find_model(["ggml-base.en.bin", "ggml-base.bin"])
_TURBO_MODEL = _find_model(["ggml-large-v3-turbo.bin", "ggml-large-v3-turbo-q5_0.bin"])
_CLIPS_PRESENT = all(clip_path(c["id"]).exists() for c in CLIPS)

_needs_free = pytest.mark.skipif(
    not (_CLI and _BASE_MODEL and _CLIPS_PRESENT),
    reason="needs whisper-cli + base.en model + the generated golden corpus",
)


@pytest.fixture(autouse=True)
def _preserve_flatpak_runtime_for_golden(monkeypatch):
    """The global test fixture clears Flatpak env vars for deterministic host tests.

    Golden ASR is different: when it is explicitly enabled inside the installed
    Flatpak runtime, it must exercise `/app/bin/whisper-cli` and `/app/share/*`.
    Preserve that runtime identity only for this opt-in golden run.
    """
    if not (_GOLDEN_ENABLED and Path("/app/bin/whisper-cli").exists()):
        return

    monkeypatch.setenv("FLATPAK_ID", "io.wayfindercollective.WayfinderAura")
    monkeypatch.setenv("WAYFINDER_FLATPAK", "1")

    import wayfinder.config as config

    monkeypatch.setattr(config, "IS_FLATPAK", True)
    try:
        import wayfinder.core.transcriber as transcriber
        monkeypatch.setattr(transcriber, "IS_FLATPAK", True)
    except Exception:
        pass


def _asr(model, wav, use_gpu):
    """Raw transcription through the real backend + the app's standard artifact
    cleanup (NO LLM post-processing)."""
    from wayfinder.core.transcriber import (
        WhisperCppBackend, clean_whisper_artifacts, normalize_whisper_caps,
    )
    backend = WhisperCppBackend(
        whisper_binary=_CLI, model_path=model, language="en",
        use_gpu=use_gpu, beam_size=5, best_of=5,
    )
    return normalize_whisper_caps(clean_whisper_artifacts(backend.transcribe(str(wav))))


@_needs_free
@pytest.mark.parametrize("clip", [c for c in CLIPS if c["category"] != "silence"],
                         ids=lambda c: c["id"])
def test_free_tier_accuracy(clip):
    """base.en (free/CPU): every clip stays under its WER ceiling AND keeps its key
    phrases — locks the transcription core against a model/prompt/cleanup regression."""
    out = _asr(_BASE_MODEL, clip_path(clip["id"]), use_gpu=False)
    w = wer(clip["reference_text"], out)
    assert w <= clip["max_wer"], (
        f"{clip['id']}: WER {w:.3f} > {clip['max_wer']} — transcription regressed.\n"
        f"  ref: {clip['reference_text']!r}\n  got: {out!r}"
    )
    missing = [p for p in clip["key_phrases"] if p not in phrase_hits(out, clip["key_phrases"])]
    assert not missing, f"{clip['id']}: dropped key phrases {missing} — got {out!r}"


@_needs_free
def test_silence_produces_no_words():
    """A silent clip must NOT hallucinate speech (whisper's classic silence failure).
    Locks the artifact-cleanup + no-speech handling."""
    silent = next(c for c in CLIPS if c["category"] == "silence")
    out = _asr(_BASE_MODEL, clip_path(silent["id"]), use_gpu=False)
    words = [t for t in out.lower().split() if t.isalpha()]
    assert not words, f"silence hallucinated words: {out!r}"


@pytest.mark.skipif(
    not (_CLI and _BASE_MODEL and _TURBO_MODEL and _CLIPS_PRESENT and _gpu_present()),
    reason="premium path needs the turbo model + a usable GPU (on-device only)",
)
def test_premium_at_least_as_accurate_as_free():
    """Premium (turbo/GPU) should be at least as accurate as free (base.en) IN
    AGGREGATE. Advisory, aggregate-only: a short clean clip can let base.en match
    or beat turbo, so this is a mean-over-corpus check, not per-clip."""
    clean = [c for c in CLIPS if c["category"] != "silence"]
    free = [wer(c["reference_text"], _asr(_BASE_MODEL, clip_path(c["id"]), use_gpu=False))
            for c in clean]
    prem = [wer(c["reference_text"], _asr(_TURBO_MODEL, clip_path(c["id"]), use_gpu=True))
            for c in clean]
    mean_free = sum(free) / len(free)
    mean_prem = sum(prem) / len(prem)
    assert mean_prem <= mean_free + _PREMIUM_AGG_EPS, (
        f"premium mean WER {mean_prem:.3f} worse than free {mean_free:.3f} "
        f"(+{_PREMIUM_AGG_EPS} slack) — GPU/turbo path regressed"
    )
