"""Researched game-chat entries for the Games tab (generated; do not edit).

Built by scripts/build_game_list.py from web research on popular Mac-playable
multiplayer games (Steam top sellers with Mac builds, plus non-Steam Mac
games). Every entry is Untested until someone tries Aura in the game.
Each tuple: (name, status, note, aliases, sources).
"""

RESEARCHED_GAMES = (
    ('7 Days to Die', 'untested',
     'Chat opens with T; press it, then dictate. Aura pastes (check in game).',
     ('7 days', '7dtd'), ('https://steamcommunity.com/app/251570/discussions/0/46476145180264955/', 'https://www.applegamingwiki.com/wiki/7_Days_to_Die')),
    ('American Truck Simulator', 'untested',
     'Text chat is in Convoy multiplayer and opens with Y; press it, then dictate. Pasting is unconfirmed (check in game).',
     ('ats',), ('https://trucksimulator.wiki.gg/wiki/Convoy_(game_mode)', 'https://www.applegamingwiki.com/wiki/American_Truck_Simulator')),
    ('ARK: Survival Evolved', 'untested',
     'The Mac version crashes on Apple Silicon, so play through cloud streaming such as GeForce Now (check in game). Global chat opens with Enter; pasting through the stream is unconfirmed (check in game).',
     ('ark', 'ark se', 'ase'), ('https://www.applegamingwiki.com/wiki/ARK:_Survival_Evolved', 'https://ark.fandom.com/wiki/Chat')),
    ('Arma 3', 'untested',
     'Chat opens with /; press it, then dictate. Aura pastes (check in game). The Mac port can lag behind Windows, so servers must run the same version.',
     ('a3', 'arma'), ('https://dev.arma3.com/ports', 'https://community.bistudio.com/wiki/Arma_3:_Field_Manual_-_Multiplayer')),
    ('Barony', 'untested',
     'Chat opens with Enter; press it, then dictate. Paste is not confirmed (check in game).',
     (), ('https://barony.wiki.gg/wiki/Console_Commands', 'https://www.baronygame.com/blog/432-voice-chat-guide')),
    ('Barotrauma', 'untested',
     'Chat opens with T for nearby crew, or R for radio with a headset; press it, then dictate. Aura pastes (check in game).',
     ('baro',), ('https://barotraumagame.com/wiki/Controls_Menu', 'https://www.applegamingwiki.com/wiki/Barotrauma')),
    ('Big Walk', 'untested',
     'Text chat opens with Enter (check in game) and works by proximity, so only nearby players or walkie-talkie partners read it. Paste is not confirmed (check in game).',
     (), ('https://bigwalk.game/faq/', 'https://store.steampowered.com/app/1478500/Big_Walk/')),
    ('Borderlands 2', 'untested',
     'Chat opens with Y; press it, then dictate. Aura pastes (check in game). The Mac version is no longer updated and only plays with other Mac players.',
     ('bl2',), ('https://steamcommunity.com/app/49520/discussions/0/882962960790003542/', 'https://support.aspyr.com/hc/en-us/articles/203396134-Borderlands-2-Mac-FAQ')),
    ('Brawlhalla', 'untested',
     'Chat opens with Enter in online lobbies and custom rooms; press it, then dictate. Paste is not confirmed (check in game).',
     ('bhal',), ('https://brawlhalla.wiki.gg/wiki/Chat',)),
    ('Divinity: Original Sin 2 - Definitive Edition', 'untested',
     'Chat opens with Enter in multiplayer; press it, then dictate. Aura pastes (check in game).',
     ('divinity', 'divinity 2', 'dos2', 'dos2de'), ('https://steamcommunity.com/app/435150/discussions/0/1473096694444611136/', 'https://www.applegamingwiki.com/wiki/Divinity:_Original_Sin_II')),
    ('Dying Light', 'untested',
     'Chat opens with Enter (not the numpad Enter); press it, then dictate. Aura pastes (check in game).',
     ('dying light 1',), ('https://steamcommunity.com/app/239140/discussions/0/604941528473974251/', 'https://www.applegamingwiki.com/wiki/Dying_Light')),
    ('Easy Red 2', 'untested',
     'Chat opens with Enter; press it, then dictate. Pasting is unconfirmed (check in game).',
     ('easy red', 'er2'), ('https://store.steampowered.com/app/1324780/Easy_Red_2/', 'https://steamcommunity.com/app/1324780/discussions/0/595142571487959861/')),
    ('Escape Simulator', 'untested',
     'Text chat opens with Enter in online co-op; press it, then dictate. Aura pastes (check in game).',
     ('es1', 'escape sim'), ('https://steamcommunity.com/app/1435790/discussions/0/3112542578516642616/',)),
    ('Escape Simulator 2', 'untested',
     'Text chat opens with Enter in online co-op (check in game). Aura pastes (check in game).',
     ('es2', 'escape sim 2'), ('https://store.steampowered.com/app/2879840/Escape_Simulator_2/', 'https://steamcommunity.com/app/2879840/discussions/0/845114064658168480/')),
    ('Euro Truck Simulator 2', 'untested',
     'In Convoy mode, chat opens with Y; press it, then dictate. Aura pastes (check in game).',
     ('ets2', 'euro truck'), ('https://trucksimulator.wiki.gg/wiki/Convoy_(game_mode)', 'https://www.applegamingwiki.com/wiki/Euro_Truck_Simulator_2')),
    ('Europa Universalis IV', 'untested',
     'Multiplayer chat opens with Tab; press it, then dictate. Paste is not confirmed (check in game).',
     ('eu 4', 'eu4', 'europa universalis 4'), ('https://eu4.paradoxwikis.com/Multiplayer', 'https://steamcommunity.com/app/236850/discussions/0/350541595108489476/')),
    ('Factorio', 'untested',
     'Chat opens with the ` key (left of 1; rebind it under Toggle chat); press it, then dictate. Aura pastes (check in game); do not start messages with /c, which runs a command.',
     ('factorio', 'space age'), ('https://wiki.factorio.com/console',)),
    ('Farming Simulator 25', 'untested',
     'Chat opens with T in multiplayer; press it, then dictate. Aura pastes (check in game).',
     ('farming sim 25', 'fs25', 'ls25'), ('https://farmingsimulator.wiki.gg/wiki/Controls/Farming_Simulator_25',)),
    ('Firestone – Idle Clicker Online RPG', 'untested',
     'Click the chat icon at the lower left (it unlocks at level 3), click the text box, then dictate. Pasting is unconfirmed (check in game).',
     ('firestone', 'firestone idle'), ('https://firestone-idle-rpg.fandom.com/wiki/Game_Chat', 'https://store.steampowered.com/app/1013320/Firestone__Idle_Clicker_Online_RPG/')),
    ('Fishing Planet', 'untested',
     'Chat opens with Tab; press it, then dictate. Paste is not confirmed (check in game).',
     (), ('https://steamcommunity.com/app/380600/discussions/0/537405286652024677/', 'https://store.steampowered.com/app/380600/Fishing_Planet/')),
    ('Fortnite', 'untested',
     'No Mac version; play through GeForce NOW or Xbox Cloud Gaming. Chat opens with Enter, but paste into the cloud stream is not confirmed (check in game).',
     ('fn', 'fortnite br'), ('https://x.com/FortniteStatus/status/1866595132247773231', 'https://www.fortnite.com/news/introducing-a-new-text-chat-experience-in-fortnite?lang=en-US')),
    ('Genshin Impact', 'not_recommended',
     'No Mac version; Mac players rely on unofficial workarounds. Co-op chat opens with Enter (check in game).',
     ('genshin',), ('https://www.applegamingwiki.com/wiki/Genshin_Impact',)),
    ('Golf With Your Friends', 'untested',
     'Chat opens with T; press it, then dictate. Aura pastes (check in game).',
     ('golf with friends', 'gwyf'), ('https://defkey.com/golf-with-your-friends-shortcuts',)),
    ('Hearts of Iron IV', 'untested',
     'Multiplayer chat opens with Tab (or click the chat box at the bottom left); open it, then dictate. Paste is not confirmed (check in game).',
     ('hearts of iron 4', 'hoi 4', 'hoi4'), ('https://steamcommunity.com/app/394360/discussions/0/1643168364648741103/',)),
    ('Heroes of the Storm', 'untested',
     'Chat opens with Enter for team chat (Shift+Enter for all chat); press it, then dictate. Aura pastes (check in game).',
     ('hots',), ('https://www.applegamingwiki.com/wiki/Heroes_of_the_Storm',)),
    ('Human Fall Flat', 'untested',
     'Chat opens with T; press it, then dictate. Aura pastes (check in game).',
     ('hff',), ('https://steamcommunity.com/app/477160/discussions/0/1488866180595566042/', 'https://www.applegamingwiki.com/wiki/Human:_Fall_Flat')),
    ('Infinity Kingdom', 'untested',
     "Click the chat box (World, Kingdom or Alliance), then dictate. On a Mac, play the App Store version, since the Steam Mac build reportedly won't launch (check in game).",
     ('ik',), ('https://www.mguwp.com/InfinityKingdom/news/3584', 'https://steamcommunity.com/app/1573360/discussions/0/3056240606699164798')),
    ('Liftoff: FPV Drone Racing', 'untested',
     'In multiplayer rooms, click the chat box first, then dictate. Aura pastes (check in game).',
     ('liftoff',), ('https://steamcommunity.com/app/410340/discussions/0/360670708789577782/', 'https://steamcommunity.com/app/410340/discussions/0/1839063537798835871/')),
    ('MapleStory', 'untested',
     'Chat opens with Enter; press it, then dictate. The Mac version is a beta for Apple Silicon, and paste support is unconfirmed (check in game).',
     ('gms', 'maple'), ('https://www.nexon.com/maplestory/news/general/40921/mac-os-beta-steam-support-notice', 'https://support-maplestory.nexon.com/hc/en-us/articles/23610205021460-Can-I-play-MapleStory-on-a-Mac')),
    ('Mechabellum', 'untested',
     'Click the chat bar at the bottom of the screen, pick All or Team, then dictate. Aura pastes (check in game).',
     (), ('https://steamcommunity.com/app/669330/discussions/0/3958161899240785018/', 'https://steamcommunity.com/app/669330/discussions/2/600777204942510747/')),
    ('Necesse', 'untested',
     'Chat opens with Enter; press it, then dictate. Aura pastes (check in game).',
     (), ('https://necessewiki.com/Multiplayer', 'https://www.applegamingwiki.com/wiki/Necesse')),
    ("No Man's Sky", 'untested',
     'Chat opens with Enter; press it, then dictate. Paste is not confirmed (check in game).',
     ('nms',), ('https://steamcommunity.com/app/275850/discussions/4/1743342466031168718/',)),
    ('Operation: New Earth', 'untested',
     'Click the chat panel and its text box, then dictate. Pasting is unconfirmed (check in game).',
     (), ('https://huntedcow.com/games/operation-new-earth', 'https://apps.apple.com/us/app/operation-new-earth/id1493578569?mt=12')),
    ('Pixel Gun 3D: PC Edition', 'untested',
     'Click the keyboard button at the bottom right to open chat, then dictate. The Mac version needs Apple Silicon, and pasting is unconfirmed (check in game).',
     ('pg3d', 'pixel gun'), ('https://store.steampowered.com/news/app/2524890/view/4699034475092602520', 'https://pixelgun.fandom.com/wiki/Chat_Mode_(PG3D)')),
    ('Realm of the Mad God Exalt', 'untested',
     'Chat opens with Enter; press it, then dictate. Aura pastes (check in game).',
     ('exalt', 'realm', 'rotmg'), ('https://gamefaqs.gamespot.com/mac/661874-realm-of-the-mad-god/answers/369979-how-to-chat',)),
    ('Root', 'untested',
     'Click the chat panel in an online match, then dictate. Aura pastes (check in game).',
     (), ('https://www.direwolfdigital.com/game-room-app/', 'https://store.steampowered.com/app/965580/Root/')),
    ('Rust', 'untested',
     'Chat opens with T (Tab switches to team chat); press it, then dictate. Aura pastes.',
     (), ('https://wiki.facepunch.com/rust/global_text_chat', 'https://www.applegamingwiki.com/wiki/Rust')),
    ('Sea of Thieves', 'not_recommended',
     "On a Mac it only runs through cloud streaming, and GeForce NOW on Mac pastes with Ctrl+V, not Cmd+V, so Aura's paste may not land (check in game). Chat opens with Enter.",
     ('sot',), ('https://www.seaofthieves.com/community/forums/topic/97728/text-chat-binding', 'https://nvidia.custhelp.com/app/answers/detail/a_id/5364/~/how-is-copy-and-paste-supported-on-geforce-now')),
    ("Sid Meier's Civilization VI", 'untested',
     'In multiplayer, click the chat panel first, then dictate. Aura pastes (check in game). Online play on Mac needs the Steam version.',
     ('civ', 'civ 6', 'civ vi', 'civ6', 'civilization', 'civilization 6'), ('https://steamcommunity.com/app/289070/discussions/4/154644349170078000/', 'https://www.applegamingwiki.com/wiki/Civilization_VI')),
    ("Sid Meier's Civilization VII", 'untested',
     'Open chat with the chat icon above the minimap, click the text box, then dictate. Pasting is unconfirmed (check in game).',
     ('civ', 'civ 7', 'civ vii', 'civ7', 'civilization', 'civilization 7', 'civilization vii'), ('https://support.civilization.com/hc/en-us/articles/37314455208339-Civilization-VII-Using-Group-Chats', 'https://support.civilization.com/hc/en-us/articles/37319705105427-Civilization-VII-Dealing-With-Bad-Behavior')),
    ('Spiral Knights', 'untested',
     'Chat opens with Enter or /; press it, then dictate. The Java Mac client has had launch problems on Apple Silicon since 2025 (check in game).',
     ('sk',), ('https://wiki.spiralknights.com/Chat', 'https://forums.spiralknights.com/en/node/124890')),
    ('Stellaris', 'untested',
     'Multiplayer chat opens with L or the Multiplayer Chat button; open it, then dictate. Paste is not confirmed (check in game).',
     ('stellaris',), ('https://stellaris.paradoxwikis.com/Hotkeys', 'https://www.applegamingwiki.com/wiki/Stellaris')),
    ('Stormworks: Build and Rescue', 'untested',
     'The Mac build is Intel-only and runs through Rosetta. Chat opens with Enter; paste is not confirmed (check in game).',
     ('stormworks',), ('https://www.applegamingwiki.com/wiki/Stormworks:_Build_and_Rescue', 'https://stormworks.fandom.com/wiki/Gameplay/Multiplayer')),
    ('Sun Haven', 'untested',
     'Chat opens with Enter; press it, then dictate. Pasting is unconfirmed (check in game).',
     (), ('https://sun-haven.fandom.com/wiki/Controls', 'https://steamcommunity.com/app/1432860/discussions/0/3818528846679649577/')),
    ('SUPREMACY: WORLD WAR 3', 'untested',
     'Open the chat panel and click its text box, then dictate. It also runs in a browser; pasting is unconfirmed (check in game).',
     ('supremacy', 'supremacy ww3', 'sww3'), ('https://store.steampowered.com/app/784950/SUPREMACY_WORLD_WAR_3/', 'https://www.playsupremacy.com/en/games/world-war-3')),
    ('Tabletop Simulator', 'untested',
     'Chat opens with Enter; press it, then dictate. Messages have a short length limit, and paste on Mac is not confirmed (check in game).',
     ('tts',), ('https://kb.tabletopsimulator.com/getting-started/in-game-communication/', 'https://steamcommunity.com/app/286160/discussions/0/412448158154804473/')),
    ('The Binding of Isaac: Rebirth', 'untested',
     'Text chat is only in the Repentance+ online co-op, which has no Mac version, so on a Mac it needs CrossOver (check in game). Chat opens with Enter.',
     ('boi', 'isaac', 'repentance', 'tboi'), ('https://bindingofisaacrebirth.wiki.gg/wiki/Online_(open_beta)', 'https://steamcommunity.com/app/250900/discussions/0/4631483020295018465/')),
    ('The Escapists 2', 'untested',
     'Chat opens with Enter (some setups use F); press it, then dictate. Paste is not confirmed (check in game).',
     ('escapists', 'escapists 2'), ('https://steamcommunity.com/app/641990/discussions/0/3069747783693033124/',)),
    ('Tibia', 'untested',
     'The Mac client is Intel-only and unsupported, so it runs through Rosetta. In Chat On mode typing goes straight to chat (in Chat Off mode press Enter first); the Mac paste shortcut is not confirmed (check in game).',
     (), ('https://www.tibia.com/common/help.php?subtopic=macosinformation', 'https://www.tibia.com/support/?subtopic=tibiarules&rule=3b')),
    ('Total War: THREE KINGDOMS', 'untested',
     'Chat opens with Y; press it, then dictate. The Mac version stopped updating in 2020 and only plays online with other Mac players (check in game).',
     ('3k', 'three kingdoms', 'tw3k'), ('https://steamcommunity.com/app/779340/discussions/0/1639787494957229948/', 'https://steamcommunity.com/app/779340/discussions/0/4070650515257222886/')),
    ('Total War: WARHAMMER', 'untested',
     'Multiplayer chat exists, but the Mac version only plays online with Mac and Linux players. Click the chat box to type, then dictate (check in game).',
     ('tww1', 'twwh', 'twwh1', 'warhammer 1', 'wh1'), ('https://community.creative-assembly.com/total-war/total-war-warhammer/forums/15-multiplayer-battles/threads/10325-are-we-ever-going-to-get-the-chat-function-back', 'https://steamcommunity.com/app/594570/discussions/0/2999920878452945990/')),
    ('Total War: WARHAMMER II', 'untested',
     'Multiplayer chat exists, but the Mac version only plays online with Mac and Linux players. Click the chat box to type, then dictate (check in game).',
     ('tww2', 'twwh2', 'warhammer 2', 'wh2'), ('https://community.creative-assembly.com/total-war/total-war-warhammer/forums/15-multiplayer-battles/threads/10325-are-we-ever-going-to-get-the-chat-function-back', 'https://steamcommunity.com/app/594570/discussions/0/2999920878452945990/')),
    ('War Thunder', 'untested',
     'Chat opens with Enter; press it, then dictate. You can send one battle chat message every 30 seconds, and pasting is unconfirmed (check in game).',
     ('wt',), ('https://www.applegamingwiki.com/wiki/War_Thunder', 'https://steamcommunity.com/app/236390/discussions/0/5019836142101277624/')),
    ('WolfQuest: Anniversary Edition', 'untested',
     'Chat opens with Enter or C (check in game); press it, then dictate. Players under 13 have no chat in public games, and pasting is unconfirmed (check in game).',
     ('wolfquest', 'wq', 'wqae'), ('https://support.wolfquest.org/help/multiplayer-gameplay-and-features', 'https://wolfquest.fandom.com/wiki/Multiplayer/Chat_Types')),
    ('World of Tanks Blitz', 'untested',
     'Battle chat opens with Enter and Tab switches channels; press Enter, then dictate. On the EU server only platoon chat works in battle, and pasting is unconfirmed (check in game).',
     ('tanks blitz', 'wot blitz', 'wotb'), ('https://wargaming.net/support/en/products/wotb/article/15399/', 'https://steamcommunity.com/app/444200/discussions/3/3773490849745367409/')),
    ('Wurm Online', 'untested',
     'Click into the chat input (Local, Kingdom or Village tab), then dictate. Aura pastes (check in game).',
     ('wurm',), ('https://www.wurmpedia.com/index.php/Chat', 'https://www.wurmonline.com/download/')),
    ('YAPYAP', 'untested',
     'Chat opens with Enter; press it, then dictate. Typed incantations also cast spells, so spelling must be exact (check in game).',
     ('yap yap',), ('https://games.gg/yapyap/guides/yapyap-secret-spells-guide/', 'https://store.steampowered.com/app/3834090/YAPYAP/')),
)
