"""
Voice Profile Learning Module for Wayfinder Aura.

Automatically learns from transcriptions to build a personal "voice profile"
that improves both transcription accuracy and post-processing style matching.

The profile is generated by an LLM that summarizes speaking patterns from
transcription history. Falls back to vocabulary extraction if no LLM is available.
"""

import json
import os
import re
import threading
import time
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

# Common English words to exclude from vocabulary extraction
# This is a minimal set - we want to catch domain-specific terms
COMMON_WORDS = {
    # Articles, pronouns, prepositions
    "a", "an", "the", "i", "me", "my", "we", "us", "our", "you", "your",
    "he", "him", "his", "she", "her", "it", "its", "they", "them", "their",
    "this", "that", "these", "those", "who", "what", "which", "where", "when",
    "why", "how", "all", "each", "every", "both", "few", "more", "most",
    "other", "some", "such", "no", "not", "only", "same", "so", "than",
    "too", "very", "just", "also", "now", "here", "there", "then",
    # Prepositions and conjunctions
    "of", "in", "to", "for", "with", "on", "at", "by", "from", "up", "about",
    "into", "over", "after", "beneath", "under", "above", "and", "but", "or",
    "nor", "yet", "so", "because", "although", "while", "if", "unless",
    # Common verbs
    "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
    "do", "does", "did", "will", "would", "could", "should", "may", "might",
    "must", "shall", "can", "need", "get", "got", "go", "going", "went",
    "come", "came", "make", "made", "take", "took", "see", "saw", "know",
    "knew", "think", "thought", "want", "like", "look", "use", "find",
    "give", "tell", "say", "said", "let", "put", "try", "leave", "call",
    "keep", "become", "show", "hear", "play", "run", "move", "live",
    # Common adjectives and adverbs
    "good", "new", "first", "last", "long", "great", "little", "own", "old",
    "right", "big", "high", "different", "small", "large", "next", "early",
    "young", "important", "few", "public", "bad", "same", "able", "well",
    "back", "even", "still", "way", "out", "really", "actually", "basically",
    # Filler words (already removed by transcription but just in case)
    "um", "uh", "ah", "like", "you know", "i mean", "kind of", "sort of",
    # Numbers
    "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    # Other common words
    "thing", "things", "time", "times", "year", "years", "people", "way",
    "day", "days", "man", "woman", "child", "world", "life", "hand", "part",
    "place", "case", "week", "company", "system", "program", "question",
    "work", "government", "number", "night", "point", "home", "water",
    "room", "mother", "area", "money", "story", "fact", "month", "lot",
    "study", "book", "eye", "job", "word", "business", "issue", "side",
    "kind", "head", "house", "service", "friend", "father", "power", "hour",
    "game", "line", "end", "member", "law", "car", "city", "community",
    "name", "president", "team", "minute", "idea", "body", "information",
    "yeah", "yes", "no", "okay", "ok", "sure", "maybe", "please", "thanks",
    "thank", "sorry", "hello", "hi", "hey", "bye", "goodbye",
}

# Profile generation prompt template
PROFILE_GENERATION_PROMPT = """Analyze these transcription samples from a single user and create a brief voice profile.

TRANSCRIPTION SAMPLES:
{samples}

Create a concise profile (2-3 sentences) that describes:
1. Their typical speaking style (formal/casual/technical)
2. Common topics or domain they discuss
3. Any notable vocabulary patterns or phrases they use

Output ONLY the profile description, nothing else. Keep it under 100 words.

Profile:"""


class VoiceProfile:
    """
    Manages voice profile learning from transcription history.
    
    Features:
    - Stores transcription history (configurable limit)
    - Extracts frequently used vocabulary
    - Generates LLM-based profile summaries
    - Provides context for transcription and post-processing
    """
    
    def __init__(
        self,
        config_dir: Optional[Path] = None,
        history_limit: int = 100,
        regen_interval: int = 20,
        min_samples_for_profile: int = 5,
    ):
        """
        Initialize the voice profile manager.
        
        Args:
            config_dir: Directory to store profile data (defaults to ~/.config/wayfinder-aura)
            history_limit: Maximum number of transcriptions to keep in history
            regen_interval: Regenerate profile every N new transcriptions
            min_samples_for_profile: Minimum samples needed before generating profile
        """
        self.config_dir = Path(config_dir) if config_dir else Path.home() / ".config" / "wayfinder-aura"
        self.profile_file = self.config_dir / "voice_profile.json"
        self.history_limit = history_limit
        self.regen_interval = regen_interval
        self.min_samples_for_profile = min_samples_for_profile
        
        # In-memory state
        self._data: Dict[str, Any] = {
            "history": [],
            "profile": {
                "summary": "",
                "vocabulary": [],
                "generated_at": 0,
                "samples_used": 0,
            },
            "transcriptions_since_regen": 0,
        }
        
        # Thread safety
        self._lock = threading.Lock()
        self._regen_in_progress = False
        
        # Load existing data
        self._load()
    
    def _load(self) -> None:
        """Load profile data from disk."""
        if self.profile_file.exists():
            try:
                with open(self.profile_file, "r") as f:
                    loaded = json.load(f)
                    # Merge with defaults to handle missing keys
                    self._data["history"] = loaded.get("history", [])
                    self._data["profile"] = {
                        "summary": loaded.get("profile", {}).get("summary", ""),
                        "vocabulary": loaded.get("profile", {}).get("vocabulary", []),
                        "generated_at": loaded.get("profile", {}).get("generated_at", 0),
                        "samples_used": loaded.get("profile", {}).get("samples_used", 0),
                    }
                    self._data["transcriptions_since_regen"] = loaded.get("transcriptions_since_regen", 0)
            except (json.JSONDecodeError, IOError) as e:
                print(f"[Voice Profile] Warning: Could not load profile: {e}")
                # Preserve the corrupt file — the next _save() would otherwise
                # overwrite it with empty defaults and silently destroy the
                # user's transcription history.
                try:
                    backup = self.profile_file.with_suffix(".json.corrupt")
                    self.profile_file.rename(backup)
                    print(f"[Voice Profile] Corrupt profile preserved at {backup}")
                except OSError:
                    pass
    
    def _save(self) -> None:
        """Save profile data to disk."""
        try:
            self.config_dir.mkdir(parents=True, exist_ok=True)
            with open(self.profile_file, "w") as f:
                json.dump(self._data, f, indent=2)
        except IOError as e:
            print(f"[Voice Profile] Warning: Could not save profile: {e}")
    
    def add_transcription(
        self,
        text: str,
        llm_callback: Optional[Callable[[str], str]] = None,
    ) -> None:
        """
        Add a new transcription to the history.
        
        Automatically triggers profile regeneration if:
        - Enough new transcriptions have accumulated
        - An LLM callback is provided
        
        Args:
            text: The transcribed text
            llm_callback: Optional function to call LLM for profile generation
                         Signature: (prompt: str) -> str
        """
        if not text or not text.strip():
            return
        
        text = text.strip()
        word_count = len(text.split())
        
        # Skip very short transcriptions (likely noise)
        if word_count < 3:
            return
        
        with self._lock:
            # Add to history
            self._data["history"].append({
                "text": text,
                "timestamp": int(time.time()),
                "word_count": word_count,
            })
            
            # Enforce history limit
            if len(self._data["history"]) > self.history_limit:
                self._data["history"] = self._data["history"][-self.history_limit:]
            
            # Track transcriptions since last regen
            self._data["transcriptions_since_regen"] += 1
            
            # Always update vocabulary (fast operation)
            self._update_vocabulary()
            
            # Save after each addition
            self._save()
            
            # Check if we should regenerate profile
            should_regen = (
                self._data["transcriptions_since_regen"] >= self.regen_interval
                and len(self._data["history"]) >= self.min_samples_for_profile
                and not self._regen_in_progress
            )
        
        # Regenerate profile in background if needed
        if should_regen and llm_callback:
            self._regenerate_async(llm_callback)
    
    def _update_vocabulary(self) -> None:
        """
        Extract frequently used uncommon words from history.
        Called automatically after adding transcriptions.
        """
        # Combine all transcription text
        all_text = " ".join(item["text"] for item in self._data["history"])
        
        # Extract words (alphanumeric, 3+ characters)
        words = re.findall(r'\b[a-zA-Z]{3,}\b', all_text.lower())
        
        # Count frequencies, excluding common words
        word_counts = Counter(
            word for word in words
            if word not in COMMON_WORDS
        )
        
        # Get top 50 most frequent uncommon words (appearing 2+ times)
        frequent_words = [
            word for word, count in word_counts.most_common(50)
            if count >= 2
        ]
        
        self._data["profile"]["vocabulary"] = frequent_words
    
    def _regenerate_async(self, llm_callback: Callable[[str], str]) -> None:
        """
        Regenerate the profile summary in a background thread.
        
        Args:
            llm_callback: Function to call LLM with the generation prompt
        """
        def regenerate():
            try:
                with self._lock:
                    if self._regen_in_progress:
                        return  # Another thread already regenerating
                    self._regen_in_progress = True
                print("[Voice Profile] Regenerating profile summary...")

                # Get samples for the prompt
                with self._lock:
                    samples = self._data["history"][-50:]  # Use last 50 for context
                
                if len(samples) < self.min_samples_for_profile:
                    return
                
                # Build the prompt
                samples_text = "\n---\n".join(
                    f"[{i+1}] {s['text']}"
                    for i, s in enumerate(samples[-20:])  # Use 20 most recent
                )
                prompt = PROFILE_GENERATION_PROMPT.format(samples=samples_text)
                
                # Call LLM
                summary = llm_callback(prompt)
                
                if summary and len(summary) > 10:
                    with self._lock:
                        self._data["profile"]["summary"] = summary.strip()
                        self._data["profile"]["generated_at"] = int(time.time())
                        self._data["profile"]["samples_used"] = len(samples)
                        self._data["transcriptions_since_regen"] = 0
                        self._save()
                    print(f"[Voice Profile] ✓ Profile updated ({len(summary)} chars)")
                else:
                    print("[Voice Profile] ⚠ LLM returned empty response")
                    
            except Exception as e:
                print(f"[Voice Profile] ✗ Profile generation failed: {e}")
            finally:
                with self._lock:
                    self._regen_in_progress = False
        
        thread = threading.Thread(target=regenerate, daemon=True)
        thread.start()
    
    def regenerate_profile(self, llm_callback: Callable[[str], str]) -> bool:
        """
        Force regenerate the profile summary.
        
        Args:
            llm_callback: Function to call LLM with the generation prompt
            
        Returns:
            True if regeneration was started, False if already in progress
        """
        with self._lock:
            if self._regen_in_progress:
                return False

        if len(self._data["history"]) < self.min_samples_for_profile:
            print(f"[Voice Profile] Need at least {self.min_samples_for_profile} samples")
            return False
        
        self._regenerate_async(llm_callback)
        return True
    
    def get_prompt_context(self) -> str:
        """
        Get the profile context to inject into prompts.
        
        Returns a formatted string suitable for prepending to whisper prompts
        or including in post-processor system prompts.
        
        Returns:
            Profile context string, or empty string if no profile yet
        """
        with self._lock:
            parts = []
            
            # Add summary if available
            summary = self._data["profile"].get("summary", "")
            if summary:
                parts.append(summary)
            
            # Add learned vocabulary
            vocabulary = self._data["profile"].get("vocabulary", [])
            if vocabulary:
                # Include top 20 vocabulary terms
                vocab_str = ", ".join(vocabulary[:20])
                parts.append(f"Common terms: {vocab_str}")
            
            return " ".join(parts)
    
    def get_vocabulary(self) -> List[str]:
        """Get the learned vocabulary list."""
        with self._lock:
            return self._data["profile"].get("vocabulary", []).copy()
    
    def get_summary(self) -> str:
        """Get the profile summary."""
        with self._lock:
            return self._data["profile"].get("summary", "")
    
    def get_history_count(self) -> int:
        """Get the number of transcriptions in history."""
        with self._lock:
            return len(self._data["history"])
    
    def get_stats(self) -> Dict[str, Any]:
        """
        Get profile statistics for display in UI.
        
        Returns:
            Dict with stats about the profile
        """
        with self._lock:
            profile = self._data["profile"]
            history = self._data["history"]
            
            total_words = sum(item.get("word_count", 0) for item in history)
            
            return {
                "history_count": len(history),
                "total_words": total_words,
                "vocabulary_count": len(profile.get("vocabulary", [])),
                "has_summary": bool(profile.get("summary")),
                "summary": profile.get("summary", ""),
                "vocabulary": profile.get("vocabulary", [])[:30],
                "generated_at": profile.get("generated_at", 0),
                "samples_used": profile.get("samples_used", 0),
                "transcriptions_since_regen": self._data.get("transcriptions_since_regen", 0),
            }
    
    def set_summary(self, summary: str) -> None:
        """
        Manually set the profile summary (for user editing).
        
        Args:
            summary: The new profile summary
        """
        with self._lock:
            self._data["profile"]["summary"] = summary.strip()
            self._data["profile"]["generated_at"] = int(time.time())
            self._save()
    
    def clear(self) -> None:
        """Clear all learned data (history and profile)."""
        with self._lock:
            self._data = {
                "history": [],
                "profile": {
                    "summary": "",
                    "vocabulary": [],
                    "generated_at": 0,
                    "samples_used": 0,
                },
                "transcriptions_since_regen": 0,
            }
            self._save()
        print("[Voice Profile] All data cleared")
    
    @property
    def is_regenerating(self) -> bool:
        """Check if profile regeneration is in progress."""
        return self._regen_in_progress
    
    @property
    def has_profile(self) -> bool:
        """Check if a profile summary exists."""
        return bool(self._data["profile"].get("summary"))
    
    @property
    def has_vocabulary(self) -> bool:
        """Check if learned vocabulary exists."""
        return bool(self._data["profile"].get("vocabulary"))


# Global instance for convenience
_voice_profile: Optional[VoiceProfile] = None


def get_voice_profile(
    config_dir: Optional[Path] = None,
    history_limit: int = 100,
    regen_interval: int = 20,
) -> VoiceProfile:
    """
    Get or create the global VoiceProfile instance.
    
    Args:
        config_dir: Directory to store profile data
        history_limit: Maximum transcriptions to keep
        regen_interval: Regenerate profile every N transcriptions
        
    Returns:
        The global VoiceProfile instance
    """
    global _voice_profile
    
    if _voice_profile is None:
        _voice_profile = VoiceProfile(
            config_dir=config_dir,
            history_limit=history_limit,
            regen_interval=regen_interval,
        )
    
    return _voice_profile


def reset_voice_profile() -> None:
    """Reset the global VoiceProfile instance (for testing)."""
    global _voice_profile
    _voice_profile = None
