"""
Voice Profile Learning Module for Wayfinder Aura.

Automatically learns from transcriptions to build a personal "voice profile"
that improves both transcription accuracy and post-processing style matching.

The profile is generated by an LLM that summarizes speaking patterns from
transcription history. Falls back to vocabulary extraction if no LLM is available.
"""

import json
import os
import re
import threading
import time
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from .wordlist import MID_WORDS, STOP_WORDS

# Vocabulary extraction weighting. The old extractor ranked words by raw
# frequency, which surfaced only ordinary English ("everything", "something",
# "looks", "stuff") — the words everyone says most. Instead we weight each term
# by how *distinctive* it is against a frequency-ranked English corpus (see
# wordlist.py for provenance):
#   - STOP_WORDS  (corpus rank <=3000)        : ordinary English, dropped outright.
#   - MID_WORDS   (rank 3001..20000)          : mid-band, kept but weighted low.
#   - distinctive tail (rank >20000 or absent): names/jargon/mishearings, high weight.
MID_WEIGHT = 1          # mid-band English earns 1 point per occurrence.
DISTINCTIVE_WEIGHT = 4  # the distinctive tail earns 4x — so a name beats a mid-band
                        # word unless that word recurs more than 4x as often.
VOCAB_LIMIT = 30        # cap on the learned list (feeds prompt context + the editor).
MIN_OCCURRENCES = 2     # a term must recur to count — one-offs are noise, not signal.

# Two-word phrases ("Wayfinder Aura", "Steam Deck") are learned alongside single
# words and compete in the SAME scored pool. They need a higher recurrence bar
# than unigrams: an exact *pair* repeats far less often than either of its words,
# and two words landing next to each other once or twice is frequently
# coincidental rather than a real term — so require more repetitions before we
# trust a phrase.
MIN_PHRASE_OCCURRENCES = 3


def _word_weight(key: str) -> int:
    """Distinctiveness weight for a single casefolded word (0 for stop words).

    Unlike the unigram path (which drops stop words outright), a phrase may
    legitimately contain one stop word ("Steam Deck"), so stop words score 0
    here and the phrase inherits its *best* word's weight via ``max()``.
    """
    if key in STOP_WORDS:
        return 0
    if key in MID_WORDS:
        return MID_WEIGHT
    return DISTINCTIVE_WEIGHT

# Curated supplement to the generated corpus tiers: the corpus is WRITTEN web
# text, so it systematically underrates SPOKEN English. Contraction left-halves
# ("doesn't" tokenizes to "doesn" + a too-short "t") mostly land in the
# distinctive tier — the worst possible place — and universal speech fillers
# sit mid-band. Neither is personal signal; drop both outright.
EXTRA_STOP_WORDS = frozenset("""
doesn didn isn wasn aren weren hasn haven hadn wouldn couldn shouldn mustn
needn ain
okay yeah yep nope alright dude guys gonna wanna gotta kinda sorta basically
literally obviously definitely honestly seriously anyway anyways
umm uhh hmm huh wow whoa
""".split())

# Profile generation prompt template
PROFILE_GENERATION_PROMPT = """Analyze these transcription samples from a single user and create a brief voice profile.

TRANSCRIPTION SAMPLES:
{samples}

Create a concise profile (2-3 sentences) that describes:
1. Their typical speaking style (formal/casual/technical)
2. Common topics or domain they discuss
3. Any notable vocabulary patterns or phrases they use

Output ONLY the profile description, nothing else. Keep it under 100 words.

Profile:"""


class VoiceProfile:
    """
    Manages voice profile learning from transcription history.
    
    Features:
    - Stores transcription history (configurable limit)
    - Extracts frequently used vocabulary
    - Generates LLM-based profile summaries
    - Provides context for transcription and post-processing
    """
    
    def __init__(
        self,
        config_dir: Optional[Path] = None,
        history_limit: int = 100,
        regen_interval: int = 20,
        min_samples_for_profile: int = 5,
    ):
        """
        Initialize the voice profile manager.
        
        Args:
            config_dir: Directory to store profile data (defaults to ~/.config/wayfinder-aura)
            history_limit: Maximum number of transcriptions to keep in history
            regen_interval: Regenerate profile every N new transcriptions
            min_samples_for_profile: Minimum samples needed before generating profile
        """
        self.config_dir = Path(config_dir) if config_dir else Path.home() / ".config" / "wayfinder-aura"
        self.profile_file = self.config_dir / "voice_profile.json"
        self.history_limit = history_limit
        self.regen_interval = regen_interval
        self.min_samples_for_profile = min_samples_for_profile
        
        # In-memory state
        self._data: Dict[str, Any] = {
            "history": [],
            "profile": {
                "summary": "",
                "vocabulary": [],
                "vocabulary_ignore": [],
                "generated_at": 0,
                "samples_used": 0,
            },
            "transcriptions_since_regen": 0,
        }

        # Thread safety
        self._lock = threading.Lock()
        self._regen_in_progress = False
        
        # Load existing data
        self._load()

        # Self-heal stale learned lists: profiles built by the old frequency-only
        # extractor are full of ordinary-English junk ("everything", "stuff",
        # "cart"). Recompute the vocabulary in memory now (no _save() here — the
        # next add_transcription()/set_ignored_words() persists it) so the cleaned
        # list is live the moment the app or the Voice Profile panel constructs
        # this object. History is required as the recompute source.
        if self._data["history"]:
            self._update_vocabulary()

    def _load(self) -> None:
        """Load profile data from disk."""
        if self.profile_file.exists():
            try:
                with open(self.profile_file, "r") as f:
                    loaded = json.load(f)
                    # Merge with defaults to handle missing keys
                    self._data["history"] = loaded.get("history", [])
                    self._data["profile"] = {
                        "summary": loaded.get("profile", {}).get("summary", ""),
                        "vocabulary": loaded.get("profile", {}).get("vocabulary", []),
                        # Default for old profile files written before the editable-vocab feature.
                        "vocabulary_ignore": loaded.get("profile", {}).get("vocabulary_ignore", []),
                        "generated_at": loaded.get("profile", {}).get("generated_at", 0),
                        "samples_used": loaded.get("profile", {}).get("samples_used", 0),
                    }
                    self._data["transcriptions_since_regen"] = loaded.get("transcriptions_since_regen", 0)
            except (json.JSONDecodeError, IOError) as e:
                print(f"[Voice Profile] Warning: Could not load profile: {e}")
                # Preserve the corrupt file — the next _save() would otherwise
                # overwrite it with empty defaults and silently destroy the
                # user's transcription history.
                try:
                    backup = self.profile_file.with_suffix(".json.corrupt")
                    self.profile_file.rename(backup)
                    print(f"[Voice Profile] Corrupt profile preserved at {backup}")
                except OSError:
                    pass
    
    def _save(self) -> None:
        """Save profile data to disk."""
        try:
            self.config_dir.mkdir(parents=True, exist_ok=True)
            with open(self.profile_file, "w") as f:
                json.dump(self._data, f, indent=2)
        except IOError as e:
            print(f"[Voice Profile] Warning: Could not save profile: {e}")
    
    def add_transcription(
        self,
        text: str,
        llm_callback: Optional[Callable[[str], str]] = None,
    ) -> None:
        """
        Add a new transcription to the history.
        
        Automatically triggers profile regeneration if:
        - Enough new transcriptions have accumulated
        - An LLM callback is provided
        
        Args:
            text: The transcribed text
            llm_callback: Optional function to call LLM for profile generation
                         Signature: (prompt: str) -> str
        """
        if not text or not text.strip():
            return
        
        text = text.strip()
        word_count = len(text.split())
        
        # Skip very short transcriptions (likely noise)
        if word_count < 3:
            return
        
        with self._lock:
            # Add to history
            self._data["history"].append({
                "text": text,
                "timestamp": int(time.time()),
                "word_count": word_count,
            })
            
            # Enforce history limit
            if len(self._data["history"]) > self.history_limit:
                self._data["history"] = self._data["history"][-self.history_limit:]
            
            # Track transcriptions since last regen
            self._data["transcriptions_since_regen"] += 1
            
            # Always update vocabulary (fast operation)
            self._update_vocabulary()
            
            # Save after each addition
            self._save()
            
            # Check if we should regenerate profile
            should_regen = (
                self._data["transcriptions_since_regen"] >= self.regen_interval
                and len(self._data["history"]) >= self.min_samples_for_profile
                and not self._regen_in_progress
            )
        
        # Regenerate profile in background if needed
        if should_regen and llm_callback:
            self._regenerate_async(llm_callback)
    
    def _update_vocabulary(self) -> None:
        """
        Extract DISTINCTIVE vocabulary from history — names, jargon, product
        terms, and two-word phrases — rather than the user's most-frequent
        ordinary English.

        Frequency alone is the wrong signal: the words a person says most
        ("everything", "something", "looks", "fix") are, unsurprisingly, common
        English and make for a useless personality profile. So each token is
        weighted by how *distinctive* it is against a frequency-ranked English
        corpus (see wordlist.py for provenance — Norvig's Google Web Trillion
        Word counts):

          - STOP_WORDS (corpus rank <=3000): ordinary English, dropped outright.
          - MID_WORDS (rank 3001..20000): mid-band, kept but weighted MID_WEIGHT.
          - the distinctive tail (rank >20000 or absent — names, jargon,
            mishearings): weighted DISTINCTIVE_WEIGHT, so 'Daan' or 'Flatpak'
            outranks a mid-band word said just as often.

        **Phrases.** Adjacent two-word phrases ("Wayfinder Aura", "Steam Deck")
        are learned into the SAME scored pool as single words, so phrases and
        words compete head-to-head on score. Adjacency is measured *per history
        entry* and *per segment* (entries are split on sentence punctuation
        ``[.!?,;:]`` first) — never across two transcriptions or across a
        punctuation break, which would fabricate pairs at the seams. Segments
        are tokenized at ALL word lengths so a short word breaks adjacency
        (``point of sale`` yields no ``point sale``), but a qualifying phrase
        needs BOTH words >=3 letters. A phrase is dropped if either word is a
        spoken-filler (EXTRA_STOP_WORDS), if BOTH words are ordinary English
        (STOP_WORDS), or if the casefolded phrase itself was ignored. A phrase's
        weight is the *max* of its two words' weights (stop words contribute 0),
        and it must recur >=MIN_PHRASE_OCCURRENCES times — a stricter bar than
        unigrams, since exact pairs repeat less and coincidental adjacency is
        common.

        Tokens keep their original case so a term is stored as its most common
        surface form ('Daan', not 'daan'; 'Wayfinder Aura', not 'wayfinder
        aura'). Words/phrases the user permanently deleted (``vocabulary_ignore``,
        compared casefolded) never re-learn, and a unigram must recur
        (>=MIN_OCCURRENCES) to count at all.
        """
        # Words/phrases the user deleted from the editor — never re-learn these.
        ignored = {w.casefold() for w in self._data["profile"].get("vocabulary_ignore", [])}

        # Per casefolded key: a running total and a tally of the surface forms.
        # Unigrams and bigrams are tallied separately (different recurrence bars
        # and filters) then merged into one scored pool below.
        uni_counts: Counter = Counter()
        uni_surfaces: Dict[str, Counter] = {}
        bi_counts: Counter = Counter()
        bi_surfaces: Dict[str, Counter] = {}

        # Case PRESERVED — surface forms matter (store "Daan", not "daan").
        # Single pass per entry: split into segments on sentence punctuation so
        # adjacency can't span a break, then tokenize each segment once.
        for item in self._data["history"]:
            for segment in re.split(r"[.!?,;:]", item["text"]):
                # ALL word lengths — a short word (e.g. "of") must occupy a slot
                # so it breaks adjacency for the phrase pass.
                words = re.findall(r"\b[A-Za-z]+\b", segment)

                # Unigrams: 3+ letters, distinctive-tail filtering as before.
                for tok in words:
                    if len(tok) < 3:
                        continue
                    key = tok.casefold()
                    if key in STOP_WORDS or key in EXTRA_STOP_WORDS or key in ignored:
                        continue
                    uni_counts[key] += 1
                    uni_surfaces.setdefault(key, Counter())[tok] += 1

                # Bigrams: adjacent within the segment, both words 3+ letters.
                for first, second in zip(words, words[1:]):
                    if len(first) < 3 or len(second) < 3:
                        continue
                    kfirst, ksecond = first.casefold(), second.casefold()
                    # Drop if either word is a spoken filler, or both are
                    # ordinary English. (A single stop word is allowed — the
                    # phrase inherits its distinctive word's weight.)
                    if kfirst in EXTRA_STOP_WORDS or ksecond in EXTRA_STOP_WORDS:
                        continue
                    if kfirst in STOP_WORDS and ksecond in STOP_WORDS:
                        continue
                    phrase_key = f"{kfirst} {ksecond}"
                    # Only the phrase itself being ignored kills it — an
                    # individual word in vocabulary_ignore does not.
                    if phrase_key in ignored:
                        continue
                    bi_counts[phrase_key] += 1
                    bi_surfaces.setdefault(phrase_key, Counter())[f"{first} {second}"] += 1

        # Merge into one pool: score = distinctiveness weight * frequency.
        scored: List[Tuple[int, int, str]] = []
        for key, count in uni_counts.items():
            if count < MIN_OCCURRENCES:
                continue
            surface = uni_surfaces[key].most_common(1)[0][0]
            scored.append((count * _word_weight(key), count, surface))
        for phrase_key, count in bi_counts.items():
            if count < MIN_PHRASE_OCCURRENCES:
                continue
            kfirst, ksecond = phrase_key.split(" ", 1)
            weight = max(_word_weight(kfirst), _word_weight(ksecond))
            surface = bi_surfaces[phrase_key].most_common(1)[0][0]
            scored.append((count * weight, count, surface))

        # Highest score first, raw count as the tiebreak.
        scored.sort(key=lambda t: (t[0], t[1]), reverse=True)

        self._data["profile"]["vocabulary"] = [
            surface for _score, _count, surface in scored[:VOCAB_LIMIT]
        ]
    
    def _regenerate_async(self, llm_callback: Callable[[str], str]) -> None:
        """
        Regenerate the profile summary in a background thread.
        
        Args:
            llm_callback: Function to call LLM with the generation prompt
        """
        def regenerate():
            try:
                with self._lock:
                    if self._regen_in_progress:
                        return  # Another thread already regenerating
                    self._regen_in_progress = True
                print("[Voice Profile] Regenerating profile summary...")

                # Get samples for the prompt
                with self._lock:
                    samples = self._data["history"][-50:]  # Use last 50 for context
                
                if len(samples) < self.min_samples_for_profile:
                    return
                
                # Build the prompt
                samples_text = "\n---\n".join(
                    f"[{i+1}] {s['text']}"
                    for i, s in enumerate(samples[-20:])  # Use 20 most recent
                )
                prompt = PROFILE_GENERATION_PROMPT.format(samples=samples_text)
                
                # Call LLM
                summary = llm_callback(prompt)
                
                if summary and len(summary) > 10:
                    with self._lock:
                        self._data["profile"]["summary"] = summary.strip()
                        self._data["profile"]["generated_at"] = int(time.time())
                        self._data["profile"]["samples_used"] = len(samples)
                        self._data["transcriptions_since_regen"] = 0
                        self._save()
                    print(f"[Voice Profile] ✓ Profile updated ({len(summary)} chars)")
                else:
                    print("[Voice Profile] ⚠ LLM returned empty response")
                    
            except Exception as e:
                print(f"[Voice Profile] ✗ Profile generation failed: {e}")
            finally:
                with self._lock:
                    self._regen_in_progress = False
        
        thread = threading.Thread(target=regenerate, daemon=True)
        thread.start()
    
    def regenerate_profile(self, llm_callback: Callable[[str], str]) -> bool:
        """
        Force regenerate the profile summary.
        
        Args:
            llm_callback: Function to call LLM with the generation prompt
            
        Returns:
            True if regeneration was started, False if already in progress
        """
        with self._lock:
            if self._regen_in_progress:
                return False

        if len(self._data["history"]) < self.min_samples_for_profile:
            print(f"[Voice Profile] Need at least {self.min_samples_for_profile} samples")
            return False
        
        self._regenerate_async(llm_callback)
        return True
    
    def get_prompt_context(self) -> str:
        """
        Get the profile context to inject into prompts.
        
        Returns a formatted string suitable for prepending to whisper prompts
        or including in post-processor system prompts.
        
        Returns:
            Profile context string, or empty string if no profile yet
        """
        with self._lock:
            parts = []
            
            # Add summary if available
            summary = self._data["profile"].get("summary", "")
            if summary:
                parts.append(summary)
            
            # Add learned vocabulary
            vocabulary = self._data["profile"].get("vocabulary", [])
            if vocabulary:
                # Include top 20 vocabulary terms
                vocab_str = ", ".join(vocabulary[:20])
                parts.append(f"Common terms: {vocab_str}")
            
            return " ".join(parts)
    
    def get_vocabulary(self) -> List[str]:
        """Get the learned vocabulary list."""
        with self._lock:
            return self._data["profile"].get("vocabulary", []).copy()

    def get_ignored_words(self) -> List[str]:
        """Get the list of learned words the user permanently deleted.

        These are auto-learned words the user removed in the editor; they are
        filtered out of future vocabulary extraction so they never re-learn.
        """
        with self._lock:
            return self._data["profile"].get("vocabulary_ignore", []).copy()

    def set_ignored_words(self, words: List[str]) -> None:
        """Replace the permanent ignore list and re-apply it immediately.

        Persists the new list, then re-runs vocabulary extraction so the learned
        list reflects the new ignores right away (the next ``get_vocabulary()``
        call already excludes them). Whitespace-only entries are dropped and the
        list is deduped case-insensitively (case and order preserved).
        """
        with self._lock:
            seen = set()
            cleaned: List[str] = []
            for word in words or []:
                if not word or not word.strip():
                    continue
                word = word.strip()
                key = word.lower()
                if key in seen:
                    continue
                seen.add(key)
                cleaned.append(word)
            self._data["profile"]["vocabulary_ignore"] = cleaned
            # Re-derive the learned list so removed words drop out immediately.
            self._update_vocabulary()
            self._save()
    
    def get_summary(self) -> str:
        """Get the profile summary."""
        with self._lock:
            return self._data["profile"].get("summary", "")
    
    def get_history_count(self) -> int:
        """Get the number of transcriptions in history."""
        with self._lock:
            return len(self._data["history"])
    
    def get_stats(self) -> Dict[str, Any]:
        """
        Get profile statistics for display in UI.
        
        Returns:
            Dict with stats about the profile
        """
        with self._lock:
            profile = self._data["profile"]
            history = self._data["history"]
            
            total_words = sum(item.get("word_count", 0) for item in history)
            
            return {
                "history_count": len(history),
                "total_words": total_words,
                "vocabulary_count": len(profile.get("vocabulary", [])),
                "has_summary": bool(profile.get("summary")),
                "summary": profile.get("summary", ""),
                "vocabulary": profile.get("vocabulary", [])[:30],
                "generated_at": profile.get("generated_at", 0),
                "samples_used": profile.get("samples_used", 0),
                "transcriptions_since_regen": self._data.get("transcriptions_since_regen", 0),
            }
    
    def set_summary(self, summary: str) -> None:
        """
        Manually set the profile summary (for user editing).
        
        Args:
            summary: The new profile summary
        """
        with self._lock:
            self._data["profile"]["summary"] = summary.strip()
            self._data["profile"]["generated_at"] = int(time.time())
            self._save()
    
    def clear(self) -> None:
        """Clear all learned data (history and profile)."""
        with self._lock:
            self._data = {
                "history": [],
                "profile": {
                    "summary": "",
                    "vocabulary": [],
                    "vocabulary_ignore": [],
                    "generated_at": 0,
                    "samples_used": 0,
                },
                "transcriptions_since_regen": 0,
            }
            self._save()
        print("[Voice Profile] All data cleared")
    
    @property
    def is_regenerating(self) -> bool:
        """Check if profile regeneration is in progress."""
        return self._regen_in_progress
    
    @property
    def has_profile(self) -> bool:
        """Check if a profile summary exists."""
        return bool(self._data["profile"].get("summary"))
    
    @property
    def has_vocabulary(self) -> bool:
        """Check if learned vocabulary exists."""
        return bool(self._data["profile"].get("vocabulary"))


# Global instance for convenience
_voice_profile: Optional[VoiceProfile] = None


def get_voice_profile(
    config_dir: Optional[Path] = None,
    history_limit: int = 100,
    regen_interval: int = 20,
) -> VoiceProfile:
    """
    Get or create the global VoiceProfile instance.
    
    Args:
        config_dir: Directory to store profile data
        history_limit: Maximum transcriptions to keep
        regen_interval: Regenerate profile every N transcriptions
        
    Returns:
        The global VoiceProfile instance
    """
    global _voice_profile
    
    if _voice_profile is None:
        _voice_profile = VoiceProfile(
            config_dir=config_dir,
            history_limit=history_limit,
            regen_interval=regen_interval,
        )
    
    return _voice_profile


def reset_voice_profile() -> None:
    """Reset the global VoiceProfile instance (for testing)."""
    global _voice_profile
    _voice_profile = None


# =============================================================================
# Editable-vocabulary helpers (pure functions — no I/O, unit-testable)
# =============================================================================
#
# The Voice Profile editor shows ONE flat list, but three kinds of terms feed it:
#
#   custom  — user-pinned terms. Stored in config["custom_vocabulary"] and fed
#             directly to whisper's initial prompt every dictation. This is how
#             the user teaches whisper a name/spelling ("Daan") it keeps mishearing.
#   ignored — auto-learned words the user deleted. Stored in the profile's
#             vocabulary_ignore list and permanently filtered from extraction so
#             the bad guess (e.g. "don") never comes back.
#   learned — auto-extracted frequent terms. Feeds the personal-tone LLM context,
#             regenerated from history after every transcription.
#
# merge_vocab_view builds the editor's list from these three; diff_vocab_edit
# splits the user's edited list back into (custom, ignored).


def merge_vocab_view(
    custom: List[str], learned: List[str], ignored: List[str]
) -> List[str]:
    """Build the flat list shown in the vocabulary editor.

    Custom (user-pinned) terms come first with case and order preserved, then
    the learned words minus any that are ignored or that case-insensitively
    duplicate a custom term. The result has no case-insensitive duplicates.

    Args:
        custom: user-pinned terms (config["custom_vocabulary"]).
        learned: auto-extracted vocabulary.
        ignored: learned words the user permanently deleted.

    Returns:
        The de-duplicated display list, custom terms first.
    """
    ignored_lower = {w.lower() for w in ignored}
    result: List[str] = []
    seen = set()

    for term in custom:
        if not term or not term.strip():
            continue
        term = term.strip()
        key = term.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(term)

    for word in learned:
        if not word or not word.strip():
            continue
        word = word.strip()
        key = word.lower()
        if key in ignored_lower or key in seen:
            continue
        seen.add(key)
        result.append(word)

    return result


def diff_vocab_edit(
    edited: List[str], learned: List[str], prev_ignored: List[str] = ()
) -> Tuple[List[str], List[str]]:
    """Split an edited vocabulary list back into (custom, ignored).

    A line is treated as a *custom* pinned term if its lowercase form is NOT one
    of the current learned words — i.e. the user typed something new (a name, a
    corrected spelling). Learned words the user removed become *ignored*.

    ``prev_ignored`` MUST be passed on every save: previously ignored words are
    already filtered out of ``learned``, so a plain learned-vs-edited diff would
    drop them from the ignore list and the extractor would resurrect them from
    history on the next dictation. They stay ignored unless the user typed them
    back into the editor (which revives them as a pinned custom term).

    Args:
        edited: the lines from the editor (one term per line).
        learned: the learned vocabulary the editor was SEEDED from (a snapshot,
            not a live re-read — words learned while the editor was open must
            not be treated as user-deleted).
        prev_ignored: the ignore list as of seeding time.

    Returns:
        (custom, ignored):
          custom  — edited lines not in learned, case/order preserved, deduped
                    case-insensitively, empty/whitespace lines dropped.
          ignored — learned words whose lowercase form is absent from the
                    edited list, plus prior ignores the user did not retype.
    """
    learned_lower = {w.lower() for w in learned}
    edited_lower = set()
    custom: List[str] = []
    seen = set()

    for line in edited:
        if not line or not line.strip():
            continue
        line = line.strip()
        key = line.lower()
        edited_lower.add(key)
        if key in learned_lower or key in seen:
            continue
        seen.add(key)
        custom.append(line)

    ignored = [w for w in learned if w.lower() not in edited_lower]
    ignored_lower = {w.lower() for w in ignored}
    for word in prev_ignored:
        key = word.lower()
        if key not in edited_lower and key not in ignored_lower:
            ignored_lower.add(key)
            ignored.append(word)
    return custom, ignored
