#!/usr/bin/env python3
"""Regenerate src/wayfinder/core/wordlist.py from the Norvig frequency corpus.

DEV-ONLY — never shipped, never imported at runtime. The generated module is
committed to the repo; rerun this only to change the tier cutoffs.

Source: https://norvig.com/ngrams/count_1w.txt — the 333,333 most frequent
English words with counts, derived from the Google Web Trillion Word Corpus
and published by Peter Norvig for public use (norvig.com/ngrams).

Usage:
    python3 scripts/gen_wordlists.py [path-to-count_1w.txt]
    (downloads the corpus if no local path is given)
"""
import sys
import urllib.request
from pathlib import Path

URL = "https://norvig.com/ngrams/count_1w.txt"
OUT = Path(__file__).resolve().parent.parent / "src" / "wayfinder" / "core" / "wordlist.py"

# Tier cutoffs — chosen empirically (2026-07-02) against a real user's junk
# vocabulary: generic conversational words topped out at rank 2464 ("fix"),
# while genuinely distinctive terms (names, tech jargon, product words) sat
# past 14,000 or were absent entirely. STOP=3000 kills all observed junk with
# margin; MID=20000 makes mid-band words need heavy repetition to surface.
STOP_CUTOFF = 3000
MID_CUTOFF = 20000
# COMMON (2026-09-30): real words a speech model spells right, so a near-miss
# of a vocabulary term ("Aeron" for "Arawn", rank ~77,500) is never one of
# them. Measured on /usr/share/dict/words: words that collided with a term's
# sound ("niece", "consul", "gripe", "yearn", "backhand") sat at 23k-59k.
COMMON_CUTOFF = 60000
MIN_LEN = 3  # the vocabulary tokenizer only emits 3+ letter words


def main() -> None:
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text()
    else:
        print(f"downloading {URL} ...")
        text = urllib.request.urlopen(URL, timeout=60).read().decode()

    stop, mid, common = [], [], []
    for rank, line in enumerate(text.splitlines(), 1):
        if rank > COMMON_CUTOFF:
            break
        word = line.split()[0]
        if len(word) < MIN_LEN or not word.isalpha():
            continue
        if rank <= STOP_CUTOFF:
            stop.append(word)
        elif rank <= MID_CUTOFF:
            mid.append(word)
        else:
            common.append(word)

    body = f'''"""English word-frequency tiers for voice-profile vocabulary extraction.

GENERATED by scripts/gen_wordlists.py — do not hand-edit; rerun the script.
Source: Google Web Trillion Word Corpus counts published by Peter Norvig
(https://norvig.com/ngrams/count_1w.txt). Cutoffs: STOP = corpus rank <= {STOP_CUTOFF},
MID = rank {STOP_CUTOFF + 1}..{MID_CUTOFF}; 3+ letter alphabetic words only (the tokenizer
never emits shorter tokens). Words in neither set are the distinctive tail —
names, jargon, mishearings — exactly what a personality profile wants.
"""

# rank <= {STOP_CUTOFF}: ordinary English — never vocabulary, no matter how often said.
STOP_WORDS = frozenset("""
{_wrap(stop)}
""".split())

# rank {STOP_CUTOFF + 1}..{MID_CUTOFF}: common-ish — needs heavy repetition to surface.
MID_WORDS = frozenset("""
{_wrap(mid)}
""".split())

# rank {MID_CUTOFF + 1}..{COMMON_CUTOFF}: still real English. Vocabulary near-miss
# snapping (transcriber.snap_near_vocabulary) never respells these.
COMMON_WORDS = frozenset("""
{_wrap(common)}
""".split())
'''
    OUT.write_text(body)
    print(f"wrote {OUT}: {len(stop)} stop, {len(mid)} mid, {len(common)} common")


def _wrap(words, width=76):
    lines, cur = [], ""
    for w in words:
        if len(cur) + len(w) + 1 > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}" if cur else w
    if cur:
        lines.append(cur)
    return "\n".join(lines)


if __name__ == "__main__":
    main()
